name: cashflowtracker
description: "Eine interaktive App zum Verfolgen und Verwalten von Cashflow in einem spielerischen Umfeld. Ermöglicht sowohl Singleplayer- als auch Multiplayer-Modus, bei dem Benutzer ihre finanziellen Strategien testen können."

publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  uuid: ^4.3.3
  firebase_core: ^2.27.1
  firebase_database: ^10.4.10
  cloud_firestore: ^4.15.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
