// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Standard Firebase-Konfigurationsoptionen für die Verwendung mit Ihrer Firebase-App.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions sind für diese Plattform nicht verfügbar.',
        );
    }
  }

  // Konfiguration für die Firebase-Web-Plattform
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOrvQHg8KKIR50eq-5JK-4JdWHiZ-B1eA',
    appId: '1:356574648937:web:2d12a5f11e0afc8bb45b9d',
    messagingSenderId: '356574648937',
    projectId: 'cashflow-53e1c',
    authDomain: 'cashflow-53e1c.firebaseapp.com',
    storageBucket: 'cashflow-53e1c.appspot.com',
    measurementId: 'G-GV4C84VWLZ',
  );

  // Konfiguration für die Firebase-Android-Plattform
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbdplKTaIrJKUmK1t2qLUfFMQvK7lQVgM',
    appId: '1:356574648937:android:dc36b9d687f48c83b45b9d',
    messagingSenderId: '356574648937',
    projectId: 'cashflow-53e1c',
    storageBucket: 'cashflow-53e1c.appspot.com',
  );

  // Konfiguration für die Firebase-iOS-Plattform
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNk8PbVe9hCvU5GHnDi_HuLTcPZ5VVVVA',
    appId: '1:356574648937:ios:8a3d1f6a0e3f5f76b45b9d',
    messagingSenderId: '356574648937',
    projectId: 'cashflow-53e1c',
    storageBucket: 'cashflow-53e1c.appspot.com',
    iosClientId: '356574648937-m5qjbn33uudpk6q42h6g1jia6k94t8qf.apps.googleusercontent.com',
    iosBundleId: 'com.example.cashflow',
  );

  // Konfiguration für die Firebase-macOS-Plattform
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNk8PbVe9hCvU5GHnDi_HuLTcPZ5VVVVA',
    appId: '1:356574648937:ios:e50a69c17bfab2a2b45b9d',
    messagingSenderId: '356574648937',
    projectId: 'cashflow-53e1c',
    storageBucket: 'cashflow-53e1c.appspot.com',
    iosClientId: '356574648937-jf9a152ek1r7i0dltgn95q95b3vqvn67.apps.googleusercontent.com',
    iosBundleId: 'com.example.cashflow.RunnerTests',
  );

  // Konfiguration für die Firebase-Windows-Plattform
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOrvQHg8KKIR50eq-5JK-4JdWHiZ-B1eA',
    appId: '1:356574648937:web:2d12a5f11e0afc8bb45b9d',
    messagingSenderId: '356574648937',
    projectId: 'cashflow-53e1c',
    authDomain: 'cashflow-53e1c.firebaseapp.com',
    storageBucket: 'cashflow-53e1c.appspot.com',
    measurementId: 'G-GV4C84VWLZ',
  );

  // Konfiguration für die Firebase-Linux-Plattform
  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyCOrvQHg8KKIR50eq-5JK-4JdWHiZ-B1eA',
    appId: '1:356574648937:web:2d12a5f11e0afc8bb45b9d',
    messagingSenderId: '356574648937',
    projectId: 'cashflow-53e1c',
    authDomain: 'cashflow-53e1c.firebaseapp.com',
    storageBucket: 'cashflow-53e1c.appspot.com',
    measurementId: 'G-GV4C84VWLZ',
  );
} 